name: flutter_webview_plugin
description: Plugin that allow Flutter to communicate with a native Webview.


homepage: https://github.com/MoRmdn/flutter_webview_plugin_fix
version: 1.0.0
maintainer: MoRmdn

environment:
  sdk: ">=2.16.1 <3.0.0"

flutter:
  plugin:
    androidPackage: com.flutter_webview_plugin
    pluginClass: FlutterWebviewPlugin

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  mockito: ^5.2.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
